services:
  mysql:
    container_name: mysqldb
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
  app:
    build: 
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/uploads:/app/src/uploads
    container_name: portfolio-back
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${MYSQL_USER}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
      IMAGENES_DIR: ${IMAGENES_DIR}

volumes:
  mysql-db:
    external: false
  
  imagenes-ferreteria:
    external: false
